on:
  push:
    branches:
      - main
    
jobs:
  
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t cowsay:v1.0 

      - name: list images
        run: echo "$(docker images)"
      
      - name: print commit tag
        run: echo "Triggered By tag:${{ github.ref_name }} "