on:
  workflow_dispatch:
    
  push:
    tags:
      - 'v*'
    
jobs:
  
  build-and-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write 
      contents: read
    steps:
    
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Build image
      #   run: docker build -t cowsay:${{ github.ref_name }} .

      # - name: List images
      #   run: echo "$(docker images)"
      # - name: Run container from the created image
      #   run: |
      #     docker run -d \
      #       --name cowsay \
      #       -p 80:8080 \
      #       cowsay:${{ github.ref_name }}
      
      # - name: Wait for the application to be ready
      #   run: |
      #     echo "Waiting for cowsay to wake up on port 80..."
      #     for i in {1..10}; do
      #       # curl the host port (80) directly from the runner
      #       if curl -s http://localhost:80 > /dev/null; then
      #         echo "✅ Container is responding perfectly!"
      #         exit 0
      #       fi
      #       echo "Container starting up... sleeping 1s"
      #       sleep 1
      #     done
      #     echo "❌ Container failed to respond on time."
      #     docker logs cowsay
      #     exit 1

      # - name: Test image
      #   run: echo $(curl localhost:80)
          
      - name: Test the container 
        run: echo "===============================done part 0ne============================================"
  # Step 1: Request temporary AWS credentials using the OIDC token
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::889867978066:role/github-actions-ecr-push-role
          aws-region: ap-south-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cowsay
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        