on:
  push:
    tags:
      - 'v*'
    
jobs:
  
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t cowsay:${{ github.ref_name }} .

      - name: List images
        run: echo "$(docker images)"
      - name: Run container from the created image
        run: |
          docker run -d \
            --name cowsay \
            -p 80:8080 \
            --health-cmd="curl -f http://localhost:8080/ || exit 1" \
            --health-interval=2s \
            --health-retries=10 \
            cowsay:${{ github.ref_name }}

      - name: Wait for container to be healthy
        run: |
          echo "Waiting for container to start up..."
          until [ "$(docker inspect --format='{{.State.Health.Status}}' cowsay)" == "healthy" ]; do
            echo "Still initializing..."
            sleep 1
          done
          echo "Container is up and running!"

      - name: Test the container  
        run: curl -v localhost:80